config/routes.rb
Rails.application.routes.draw do

  root 'users#show'

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'user/:id' => 'users#show'
  get '/mantra', to: 'mantras#new'
  get '/journals', to: 'journals#new'
  get '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  get '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  
  resources :users
  resources :mantras

  resources :journals
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email Sent with Password Reset Instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email Address Not Found"
      render 'new'
    end
  end

  def edit
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>
<p>Find me in app/views/password_resets/edit.html.erb</p>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot Password") %>
<h1> Forgot Password </h1>

<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |m| %>
      <%= m.label :email %>
      <%= m.email_field :email, class: 'form_control' %>

      <%= m.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>